### ISSUE TITLE
unexpected TaskCancelation in console

### ISSUE THREAD

**Issue by kellyselden** [machty/ember-concurrency#146]
I’m seeing `TaskCancelation: TaskCancelation` errors in my fastboot logs. One of the tasks causing it is:

```js
    loadIruWord: task(function * () {
        let result = yield get(this, 'store').findAll('iruWord');
        if (result !== null) {
            let filtered = this.filterWords(result, get(this, 'adjectivesToRemove'));
            set(this, 'words', filtered);
        }
        this.send('getIRUCount');
    }).on('init'),
```

Normally I would look for incorrect `.then()` usage, but I don’t see anything wrong with this task.

Narrowing down the task responsible, I start on the line triggering it `value = new Error(TASK_CANCELATION_NAME);`

and then go up the call stack to `taskInstance.cancel();` in `spliceTaskInstances`

and `taskInstance._origin._propertyName` is the task in question `loadIruWord`

**Comment by jbescoyez** [comment]
@kellyselden I am experimenting the same issue. Have you found a solution/workaround?

**Comment by kellyselden** [comment]
No

**Comment by Guaker13** [comment]
@kellyselden Follow those instructions to get rid of this issue https://github.com/machty/ember-concurrency/blob/d7347cfa1e4658a3a7acf53fe6dfdd65e4192eea/addon/-task-instance.js

**Comment by kellyselden** [comment]
@Guaker13 Which bit are you referring to, the didCancel section?

**Comment by Guaker13** [comment]
Yes, and the way to use it in the catch callback of the performed task ;)

Here is a an example of implementation with which you should get rid of the TaskCancelation error since it will only throw an error if `e.name != 'TaskCancelation'`:
`  myTask: task(function * (args) {
    try {
      // ...
      // let result = yield get(this, 'store').findAll('model');
      // return ...
    }catch(e) {

    }finally {

    }
  }).keepLatest(),

  didCancel(e) {
    return e && e.name === 'TaskCancelation';
  },

  performMyTask(args) {
    return this.get('myTask').perform(args).catch((e) => {
      if (!this.get('didCancel')(e)) { throw e; }
    });
  }`

**Comment by monovertex** [comment]
I understand the above explanation and it seems to work, but I am confused as to why and when is that exception thrown. I tested with the following controller:

```
import Ember from 'ember';
import { task, timeout } from 'ember-concurrency';

let Test = Ember.Object.extend({
    testTask: task(function* () {
        console.log('started');
        yield timeout(1000);
        console.log('finished');
    }).restartable(),

    perform() {
        return this.get('testTask').perform();
    },
});

export default Ember.Controller.extend({

    actions: {
        perform() {
            let test = Test.create();

            test.perform();
            test.perform();
            test.perform();
            test.perform();
            test.perform();
        }
    }

});
```

And this doesn't throw an error at all. Considering it's performed multiple times, why doesn't it throw the restartable exception?

![image](https://cloud.githubusercontent.com/assets/1837605/26340778/de2ea3ca-3f98-11e7-82ee-ec948eb49d02.png)

**Comment by machty** [comment]
I'd recommend that anyone seeing these errors upgrade to the latest EC, which provides much more descriptive errors as to which task got canceled and why.

To reiterate: people should only be seeing this error if somewhere along the line, someone calls `.then()` on the TaskInstance returned from a `someTask.perform()`. Either this is your code (like in @Guaker13's example), or it's library code.

@kellyselden you mentioned this was fastboot; perhaps you're passing `loadIruWord.last` (or something similar) to some component (or anyone who will call `.then()`) via the template, and since fastboot doesn't know to wait for tasks to run to completion, it's tearing down everything and canceling the task?

**Comment by machty** [comment]
@monovertex pointed out to me a subtler case which occurs when `await`ing a task instance in an async function.

Still not sure what the root cause is in @kellyselden's case, but for everyone's benefit I wrote up an explanatory [docs page](http://ember-concurrency.com/#/docs/task-cancelation-help) about the issue and just released a new version of EC that includes a link to this page in the TaskCancelation error text.

**Comment by kellyselden** [comment]
I don't know if this is an issue in the newer versions, so I will close for now.

**Comment by jkeen** [comment]
I'm getting this error on EC`0.8.22` when trying to defer rendering in fastboot on a component that loads data. It happens when I call `this.fastboot.deferRendering(this.fetch.last)`
