### ISSUE TITLE
extend task with a modifier

### ISSUE THREAD

**Issue by ruz** [machty/ember-concurrency#149]
Hi,
Want to add a custom modifier and can not figure out how to inject it. Any help?

**Comment by machty** [comment]
Support for this is still somewhat limited but take a look at how `ember-concurrency-test-waiter` did it: https://github.com/bendemboski/ember-concurrency-test-waiter/blob/master/addon/define-modifier.js

**Comment by ruz** [comment]
ha-ha, this is exactly what I was looking for :) I just ended up with "wait for all tasks mode", but want to be able to mark tasks to be waited or not.

**Comment by maxfierke** [comment]
Hi there! I'm going through and closing out old/stale issues that may no longer be relevant due to changes in the ember-concurrency or the larger Ember ecosystem.

For posterity: At EmberConf 2019, Issac Ezer gave a talk about [composable ember-concurrency tasks](https://medium.com/@isaacezer/ember-composable-concurrency-b460606f81ee) which covers how to implement your own modifiers (and references the above approach from ember-concurrency-test-waiters). This maybe be useful for anyone looking to implement their modifiers/decorated tasks.
