### ISSUE TITLE
dealing with timeouts in ember tests

### ISSUE THREAD

**Issue by jakeonfire** [machty/ember-concurrency#160]
what we've done is turn all `Ember.run.later`s to `Ember.run.next`s, which helps for anything that uses the former to delay things. it makes our whole test suite much snappier (e.g. our flash messages stay open for 1 tick/run-loop) and causes no issues. and `ember-concurrency`s `timeout`s are then also 1 tick/run-loop.

in `test-helper.js`:
```js
Ember.run.later = Ember.run.next;
```

[similarly we've turned off jQuery animations via `Ember.$.fx.off = true`]

unfortunately not something i can see `ember-concurrency` setting by default, but hopefully it will be a good solution for others.

**Comment by yoavfranco** [comment]
@jakeonfire I am nominating you for a Nobel prize. You, sir, are the unsung hero of asynchronous testing!

**Comment by maxfierke** [comment]
Hi there! I'm going through and closing out old/stale issues that may no longer be relevant due to changes in the ember-concurrency or the larger Ember ecosystem.

Since this issue was opened, various community solutions have emerged that allow providing more control over how you can test code that uses ember-concurrency tasks:

* [`ember-concurrency-test-waiter`](https://github.com/bendemboski/ember-concurrency-test-waiter) makes Ember test helpers "aware" of running Ember concurrency tasks, so things like `await settled()` will work with tasks instrumented by ember-concurrency-test-waiter.
* [`milestones`](https://salsify.github.io/milestones/docs/ember#ember-concurrency) introduces "synchronization points" and allows for control over the advancement of asynchronous code in development and test, including support for use with ember-concurrency tasks.
