### ISSUE TITLE
waitForEvent should work when only `.on` is provided, not just `.one`

### ISSUE THREAD

**Issue by machty** [machty/ember-concurrency#164]
Tried to use `waitForEvent` on a Stripe Element object but it failed the following check:

https://github.com/machty/ember-concurrency/blob/master/addon/utils.js#L3-L7

We should support objects that have `.on` and `.off`, in addition to `.one`.

**Comment by elwayman02** [comment]
This appears to be the only place `one` is used:

https://github.com/machty/ember-concurrency/blob/6b216f7e359a286e41e58d04bf1034a3e0f403a0/addon/-wait-for.js#L61

What this will need to do instead is likely execute `one` if it exists, otherwise execute `on` and wrap the callback such that it does a teardown after firing the event it's waiting for.
