### ISSUE TITLE
RFC: Support for yielding to thunks

### ISSUE THREAD

**Issue by ming-codes** [machty/ember-concurrency#169]
tl;dr `let time = yield requestAnimationFrame`

A thunk, in the context of JavaScript, is a function that takes a callback function. It is an alternative to Promise to handle asynchronous operation, except the callback is allowed to be called synchronously.

`requestAnimationFrame` just happens to fulfill that signature. The new `requestIdleCallback` would also work. This opens up more possibilities to e-c's use cases.

**Comment by Cryrivers** [comment]
I suspect this is not implemented yet because one of `ember-concurrency`'s goals is `yield`ing cancelable tasks. In your case there is no way for `e-c` knows how to cancel `requestAnimationFrame`. So `e-c` might contradicts with its own design purpose if it supports thunks.

A potential solution for your case is to make a wrapper task for `requestAnimationFrame`:

```js
import Ember from 'ember';
/**
 *
 * Yielding `animationFrame` will pause a task
 *
 * ```js
 * export default Component.extend({
 *   myTask: task(function * () {
 *     while (true) {
 *       console.log("Hello!");
 *       const timestamp = yield animationFrame();
 *     }
 *   })
 * });
 * ```
 *
 */
export default function() {
  let animationFrameId;
  let promise = new Ember.RSVP.Promise(r => {
    animationFrameId = window.requestAnimationFrame(r);
  });
  promise.__ec_cancel__ = () => {
    window.cancelAnimationFrame(animationFrameId);
  };
  return promise;
}
```

The code is taken from my addon `ec-animation-frame` ([Link here](https://github.com/Cryrivers/ec-animation-frame/blob/master/app/index.js) if you are interested). If you trust me (hopefully), you can run `ember install ec-animation-frame` to use it.

**Comment by ming-codes** [comment]
Promises are not cancellable, yet that is supported. This contradicts with the goal of yielding cancellable tasks. If by cancel you mean just ignores the scheduled event, then we can apply the same with thunks by just render the passed in callback inert.

**Comment by ming-codes** [comment]
Looks like this feature is released 😄

I'll close the ticket.
