### ISSUE TITLE
any plan to use async/await instead of generator/yield

### ISSUE THREAD

**Issue by sarbbottam** [machty/ember-concurrency#178]
Thank you for ember-concurrency. 

Please excuse my ignorance, I am just getting started.

>The behavior of yielding promises within task generator functions is designed to closely follow the behavior of the proposed `async/await` syntax, but instead of `async` function, you use `function *`, and instead of `await`, you use `yield`.

Now that `async/await` is [mainstreamed](http://caniuse.com/#search=await), is there any chances of using `async/await` instead of `generator/yield`.

**Comment by machty** [comment]
@sarbbottam async functions aren't (yet) cancelable, which is crucial functionality required by e-c; if/when async fns become cancelable then we can use async fns as task functions.

**Comment by sarbbottam** [comment]
Thanks, @machty for clarifying.

**Comment by santanapaulo** [comment]
@machty I'd like to understand a few more about why e-c is using generators instead async/await. So, you said to @sarbbottam that it is being used because of the cancellable feature. Does it mean the **return** function of a generator? Behind the scenes, does it gets triggered when a generator promise gets failed?
