### ISSUE TITLE
timeout function issue

### ISSUE THREAD

**Issue by CezaryH** [machty/ember-concurrency#232]
Hey,
there's an issue with timeout function in utils.js after production build with target set to last 1 chrome version only.

![image](https://user-images.githubusercontent.com/1262544/39996739-dcfe3b68-5780-11e8-848e-2e1972bb746f.png)
For demo open console and go to 
https://cezaryh.github.io/ember-concurrency-utils-bug/

there's bug in ember-concurrency/utils module in timeout function. After minification it looks like this:

```
e.timeout = function(e) {
    let t = new Ember.RSVP.Promise((t)=>{
      n = Ember.run.later(t, e)
    }), n;
    return t.__ec_cancel__ = ()=>{
      Ember.run.cancel(n)
    }
    , t
  }
``` 
which causes error "n is not defined".

but the same code copied to other file (https://github.com/CezaryH/ember-concurrency-utils-bug/blob/master/app/utils.js) does not throw an error, and is minified differently 

```
a.timeout = function(a) {
    let b, c = new Ember.RSVP.Promise((c)=>{
      b = Ember.run.later(c, a)
    });
    return c.__ec_cancel__ = ()=>{
      Ember.run.cancel(b)
    }
    ,c
  }
```
in this case "b" is defined

that happens when build target is "last 1 Chrome versions"

config/targets.js
```
module.exports = {
  browsers: [
    'last 1 Chrome versions'
  ]
};
```

**Comment by machty** [comment]
You're talking about a production build of an Ember app that uses ember-concurrency as an addon, right?

I'm not sure where to start looking but this seems like a minifier/autoprefixer bug rather than an e-c bug; I'd recommend looking at the ember-cli issues first. In any case, let me know what you find out.

**Comment by CezaryH** [comment]
Hi @machty,
Yes, that's correct.

I'm looking at ember-cli as well, but I'm not able to reproduce that issue in any other case.
Even in the same app I have copy of e-c utils code and it's working fine

**Comment by maxfierke** [comment]
Hi there! I'm going through and closing out old/stale issues that may no longer be relevant due to changes in the ember-concurrency or the larger Ember ecosystem.

It sounds likely this was caused by a bug with uglify or other minifer used with ember-cli. I'm going to close this out, but feel free to comment to reopen if there's a way to reproduce this.
