### ISSUE TITLE
Questions about importing tasks from their own files

### ISSUE THREAD

**Issue by xtagon** [machty/ember-concurrency#272]
Hi, 

I apologize if this has been answered before, I was looking through the issues and didn't find it.

Are there any gotchas I should know about before putting task definitions in their own files? E.g. `app/tasks/my-task.js` and then importing as `import myTask from "my-app/tasks/my-task"`?

I understand that the concurrency is locked to the object that owns the task. If I have two different objects with this import and I use it in the object properties, do both objects own the same task definition (shared concurrency lock), or do they have separate concurrency patterns?

Is it better to export a generator function from the task file and wrap with `task(...)` in each usage, or export using the `task(...)` helper with the generator function in the task file and just add modifiers to each usage in different objects?

Thanks in advance

**Comment by maxfierke** [comment]
Hi there! I'm going through and looking to close out any old/stale issues that may no longer be relevant due to changes in the ember-concurrency, the larger Ember ecosystem, or self-resolution.

Were you able to find an answer to this @xtagon? Is there anything you could share back that could be useful for folks looking to do the same thing?

**Comment by xtagon** [comment]
Without a direct answer from someone more educated on the code itself, the best I can find is the fact that a shared function is used in the example docs, as seen here: http://ember-concurrency.com/docs/task-concurrency

**Comment by xtagon** [comment]
And that's good enough for me if you want to close this, although I would be curious to find out exactly what the runtime differences are between the pattern of sharing generator functions vs sharing task definitions using the `task` helper.

**Comment by maxfierke** [comment]
@xtagon The answer appears to be: Yes, you can export a `task(...)` and re-use it across components, and they will each maintain their own state. At least, in this limited Twiddle: https://ember-twiddle.com/576423fc578d8023b943ccf1c28bc9df I didn't test it extensively, so perhaps there's some hidden gotchas. However, because `task(...)` returns a `TaskProperty`, which is a type of `ComputedProperty`, the semantics are similar to a computed property macro like `reads` or `mapBy`.

I think this has something to do with property descriptors. I don't know enough about them to speak intelligently but perhaps there's a "late-binding" thing that happens on assignment as a property on an object.

**Comment by xtagon** [comment]
Thank you! That helps a lot 👍
