### ISSUE TITLE
[example request] Basic usage with `ember-ajax`

### ISSUE THREAD

**Issue by lolmaus** [machty/ember-concurrency#32]
There are example that uses low-level `xhr`, but the most common use case (apart from Ember Data) is [ember-ajax](https://github.com/ember-cli/ember-ajax).

What is the most efficient and compact way of using `ember-concurrency` with `ember-ajax`? Is it possible to cancel `ember-ajax` requests?

**Comment by machty** [comment]
Related: https://github.com/ember-cli/ember-ajax/issues/67#issuecomment-191013780

**Comment by alexlafroscia** [comment]
@lolmaus currently, we don't have a way to cancel requests.  It's something we're looking to add though, specifically to support usage with `ember-concurrency`.

**Comment by lolmaus** [comment]
@alexlafroscia 
![image](https://cloud.githubusercontent.com/assets/200884/13697654/eab279e0-e77f-11e5-9774-b549fa2e7a02.png)

**Comment by alexlafroscia** [comment]
It's not exactly simple to just "add support" for it.  We basically have two options:

1. Expose the `XHR` object after the request is made, instead of resolving it with `raw`, which sort of defeats the point of `ember-ajax`. We're trying to abstract that away in order to swap out `$.ajax` with `fetch` in the long run, so anything that's `$.ajax`-specific is moving in the wrong direction.
2. Implement the Promise that is returned from `ajax.request` as a cancellable Promise, which is what we will actually do.  However, cancellable Promises aren't part of the official specification, so that's something we would need to add ourselves.

We'll get there, and soon, but there's currently a few other larger things that we want to get done first.

**Comment by lolmaus** [comment]
Thank you for explanations, @alexlafroscia.

Many JS developers rant at promises for the lack of cancellability in promises. Bluebird, for example, [already implements cancellability](http://bluebirdjs.com/docs/api/cancellation.html). What do you think about fighting for adding identical functionality into RSVP?

**Comment by alexlafroscia** [comment]
Probably would be a good idea.  However, we have to work with what we've got.  Thanks for linking to that Bluebird information -- I wouldn't want to stray from using RSVP, since that's what the whole Ember community us used to, but it's good to know what else is out there.

**Comment by machty** [comment]
Nothing really actionable here on the ember-concurrency side.

**Comment by robclancy** [comment]
ember-ajax now supports this on master. Not sure if there are plans for ember-concurrency to cancel the requests itself when things like a component gets destroyed.

Here is an example (changed code from what I actually used so could be mistakes)

```js
    let promise;
    try {
      promise = this.requestSomethingWithEmberAjax();
    } finally {
      if (promise.xhr.readyState !== 4) {
        promise.xhr.abort();
      }
    }
```

**Comment by machty** [comment]
@robclancy that looks good to me; do you even need to check ready state? In my experience `abort()`ing a complete XHR just no-ops.

In an upcoming version of EC it'll be possible to import a symbol from EC and use it to implement a method on objects or their prototypes so that when they're yielded in an EC task, it'll provide EC with extra information as to how to cancel them.

The goal is that you'd be able to implement this fn on [ember-ajax's promise](https://github.com/ember-cli/ember-ajax/blob/master/addon/-private/promise.js), something like

```
https://github.com/ember-cli/ember-ajax/blob/master/addon/-private/promise.js

import AJAXPromise from 'ember-ajax/-private/promise';
import { YIELDABLE } from 'ember-concurrency'; // this API not on master yet

AJAXPromise.protoype[YIELDABLE] = function * (promise, taskInstance) {
    try {
      return yield this.requestSomethingWithEmberAjax();
    } finally {
      promise.xhr.abort();
    }
}
```

This would make it so that anywhere else in your code you could just write

```
  ajax: Ember.inject.service(),
  myTask: task(function * () {
    let a = yield this.get('ajax').request('/posts');
    let b = yield this.get('ajax').request('/posts');
    let c = yield this.get('ajax').request('/posts');
  })
```

I'm not 100% I'll be exposing this since it's kind of changes behavior everywhere and might "over-cancel" in some cases but I'm leaning towards adding it.

**Comment by robclancy** [comment]
Yeah that is something I would use I think if offered. 

Editing my comment to remove ready state stuff incase someone finds themself in this issue.

**Comment by alexlafroscia** [comment]
If there's something that `ember-ajax` can do to make it easier to work with `yield` then I'd love to support that out-of-the-box. I just wouldn't want to require `ember-concurrency` as a hard dependency of that add-on.

**Comment by machty** [comment]
@alexlafroscia the only thing would be moving the Ajax Promise class out of a `-private` module so that its prototype could be reliably extended.

**Comment by alexlafroscia** [comment]
Yeah, we could do that. It's in `-private` right now because it's not something consumers should access directly, but if you'd like to extend it like that, we could relocate it and ensure that it's API has no breaking changes in less-than-major versions.

**Comment by robclancy** [comment]
Things like that are super annoying. I'm a programmer not a "consumer". And if my app is this "consumer" it is made by me and other programmers. 

I see no reason to make it private. Can't even do basic stuff like `typeof` without it feeling hacky if you use private and then instead have to use `.constructor.name`.

**Comment by AKST** [comment]
> I see no reason to make it private.

@robclancy it's just additional surface area maintainers are responsible for and it may not be in a state to commit to a stable API, that's why it's private. It being private doesn't stop you from using it, it just means if you use it, you use it at the risk of your application breaking between library updates.

**Comment by alexlafroscia** [comment]
> It being private doesn't stop you from using it, it just means if you use it, you use it at the risk of your application breaking between library updates.

Bingo. Obviously, your app can still import from stuff under `-private`, but if the API changes, it's not a semver violation. That's the convention that a number of Ember Addons have adopted, anyway, so that's what `ember-ajax` is doing too, since most people wouldn't interact with the `AJAXPromise` class directly.

> Can't even do basic stuff like `typeof` without it feeling hacky if you use private and then instead have to use `.constructor.name`

I don't see how either of those things are related to the module being located under `-private`
