### ISSUE TITLE
Merge in ember-concurrency-decorators

### ISSUE THREAD

**Issue by wagenet** [machty/ember-concurrency#326]
The docs for ember-concurrency-decorators say they'll likely be merged back in to ember-concurrency itself. Is this still planned? If so, what's blocking it?

**Comment by buschtoens** [comment]
Hi 👋

I'm the guy that wrote [this statement](https://github.com/machty/ember-concurrency-decorators#do-i-need-this-addon), which I think you're referring to:

> Eventually, all work in `ember-concurrency-decorators` will likely flow back into `ember-concurrency` at some point. Until then, we want to mature and test-drive the API here first.

The major thing missing IMO is https://github.com/machty/ember-concurrency-decorators/pull/56, which would add proper support for TypeScript / type-safety. It in turn is blocked by https://github.com/machty/ember-concurrency/pull/319, which would add the type definitions upstream here. There's also some changes required because of the new [Stricter Generators in TypeScript 3.6](https://devblogs.microsoft.com/typescript/announcing-typescript-3-6/#stricter-generators), which potentially are incompatible with prior TS versions.
I don't think the lack of TS support is a reason to not merge `ember-concurrency-decorators` back into `ember-concurrency` though.

However, I personally don't know yet, if the current API of `ember-concurrency-decorators` is perfect yet. Considering we want to bake "nice" decorator support into `ember-concurrency` itself, do we only port over `@task`, or also all other decorators? Do we want to try a completely different API first?

**Comment by wagenet** [comment]
@buschtoens while I agree with the concern about switching APIs up too much, I also think non-e-c-d version is pretty terrible, so IMO it might just be worth picking something.

**Comment by maxfierke** [comment]
IMO if the current e-c-decorators approach using stage-1 decorators is likely to continue working for future stages of decorators, then it feels pretty well-baked to me: cleaner than current approach, already supports third-party e-c add-ons like `e-c-test-waiters` and `e-c-retryable`, and feels pretty intuitive if you've used e-c for a bit.

Perhaps the TypeScript question should remain separate, if possible? Unless the choice of an official decorator would preclude some level of TypeScript support (which @buschtoens, maybe you're getting at with that article on Stricter Generators). There are likely other questions around TypeScript support that need to be answered (and if/when #302 gets merged, that'll probably change the conversation a bit too.)

definitely needs a weigh-in from @machty, though

**Comment by maxfierke** [comment]
Closing, as these decorators now exist in 2.0.0-rc.1+ (including 2.0.0, which has just been released.)
