### ISSUE TITLE
[example request] Using with async button

### ISSUE THREAD

**Issue by lolmaus** [machty/ember-concurrency#33]
[ember-async-button](https://github.com/dockyard/ember-async-button) is a super handy component that gives you a link/button with default, pending, failed and success states.

It should naturally integrate with `ember-concurrency`. I wonder if it's already possible to use the two with zero boilerplate or there must be some changes made to `ember-async-button` to minimize glue code?

**Comment by lolmaus** [comment]
Wait, does `ember-concurrency` deprecate `ember-async-button`? :scream:

**Comment by lolmaus** [comment]
Hmm, `ember-async-button` has success and failed states which `ember-concurrency` does not provide?

**Comment by chnn** [comment]
I was trying this out recently. I didn't create anywhere near as thoughtful or complete of an API as ember-async-button, but you can [see my experiment here](https://gist.github.com/chnn/cfa0e19383c740a9763bfc299f2c8364).

**Comment by lolmaus** [comment]
@chnn Now imagine my dog pulled out my WiFi router's cord and the network request failed. How will I know that it failed?

**Comment by maxfierke** [comment]
Hi there! I'm going through and closing out old/stale issues that may no longer be relevant due to changes in the ember-concurrency or the larger Ember ecosystem.

[`ember-async-button`](https://github.com/dockyard/ember-async-button) has been deprecated as-of March 2018, but it is quite easy to replicate the functionality using ember-concurrency (borrowing example from async-button readme). Here's an example for posterity's sake:

```hbs
<button type="button" onClick={{perform myTask}} disabled={{myTask.isRunning}}>
  {{#if myTask.isRunning}}
    Saving...
  {{else if myTask.last.isSuccessful}}
    Saved!
  {{else if myTask.last.isError}}
    Submission failed
  {{else}}
    Submit
  {{/if}}
</button>
```
