### ISSUE TITLE
Can't access property "lastSuccessful", this[taskName] is undefined

### ISSUE THREAD

**Issue by esbanarango** [machty/ember-concurrency#420]
### 🐞 Describe the Bug
When using the `@lastValue` decorator and passing the *path* of a task. There is an error:

**Note:** This was working before with `ember-concurrency-decorators`.

### 🔬 Minimal Reproduction
```js
export default class MyService extends Service {
  @dropTask
  *myTask() {
    yield null;
  };
}
```

```js
import { lastValue } from 'ember-concurrency';

export default class MyComponent extends Component {
  @service myService;
  @lastValue('myService.myTask') value;
}
```

<img width="788" alt="Screen Shot 2021-04-08 at 8 08 30 PM" src="https://user-images.githubusercontent.com/1156865/114114334-4a17d100-98a6-11eb-8ab6-057313604d72.png">

### 🌍 Environment

- "ember-source": "3.26.1",
- "ember-concurrency": "2.0.3"

**Comment by maxfierke** [comment]
Thanks for the heads up about this! I've opened a PR to document this as something that's been removed in ember-concurrency v2, as restoring the behavior would rely on using `Ember.get` or implementing our own support for chained property access here. I think the recommendation would be to refactor this so that it can read a property directly on the component, e.g.:

```
import { lastValue } from 'ember-concurrency';

export default class MyComponent extends Component {
  @service myService;
  get myServiceTask() { return this.myService.myTask; }
  @lastValue('myServiceTask') value;
}
```

Or otherwise, you could put the lastValue on the class as a property if you're reading it a lot / don't need to expose components to the task:

``` 
import { lastValue } from 'ember-concurrency';

export default class MyService extends Service {
  @dropTask
  *myTask() {
    yield null;
  };
  @lastValue('myTask') myTaskValue;
}
```
