### ISSUE TITLE
Enqueue one task and drop the rest?

### ISSUE THREAD

**Issue by cibernox** [machty/ember-concurrency#48]
I found the next scenario. I have a form that saves on blur on any `onchange` of it's inputs. In other words, as the user moves between fields, every time an input is blurred to focus the next and there was a change, the model is saved.

If a change occurs while the previous save is still ongoing, I want to enqueue another save, but once I have one enqueued saved, there is no point in enqueuing more, since whenever that task is performed, the save will contain all accumulative changes.

Is there any way of getting a `task().enqueueNoMoreThan(N)`?

**Comment by machty** [comment]
I believe this is the undocumented `.keepLatest()` task modifier (I stopped documenting it since it's much less common a use case). Please try it out and lemme know if it suits your needs, and I might add it back to the docs.

**Comment by adibsaad** [comment]
@machty I was looking for something like this. I wish it was documented as it would have saved me some time.

Just to let you know, my use case was basically just calling model.save(), but in my app, the model has a hex digest that must match whatever's in the database in order to be allowed to update. So without ember-concurrency, calling save() multiple times before the one before each call finishes will cause it to fail. ember-concurrency solves this but using enqueue() means that all save() calls generate a POST request. To be efficient, I just want the first and last calls to go through, so keepLatest() works perfectly for me.

**Comment by machty** [comment]
I've documented `keepLatest`. I believe what @cibernox was asking for is essentially `keepFirst`, which doesn't yet exist, but since I think keepLatest solves the problem here, I'll close this until lots of people start requesting `keepFirst`.
