### ISSUE TITLE
Ember 4.8 types preview issue

### ISSUE THREAD

**Issue by machty** [machty/ember-concurrency#510]
https://blog.emberjs.com/announcing-official-typescript-types-public-preview/

```
../node_modules/ember-concurrency/addon/index.d.ts:379:11 - error TS2315: Type 'ComputedProperty' is not generic.

379   extends ComputedProperty<T> {
              ~~~~~~~~~~~~~~~~~~~

../node_modules/ember-concurrency/addon/index.d.ts:558:47 - error TS2315: Type 'ComputedProperty' is not generic.

558 export interface TaskGroupProperty<T> extends ComputedProperty<TaskGroup<T>> {
```

Issue is due to ComputedProperty's Get type parameter being removed. We don't have a solution yet but see here for further discussion:

https://discord.com/channels/480462759797063690/484421406659182603/1062000162341396481

**Comment by gitKrystan** [comment]
I was tinkering with this today and came to the same conclusion as you did in https://discord.com/channels/480462759797063690/484421406659182603/1062000162341396481 : Trying to fix this within e-c's types breaks `get`'s "unwrapping" of task properties into tasks.

Since the native types dropped support for the old object model, which I believe will break the unwrapping anyway, I'm wondering if there is any remaining benefit to inheriting from `ComputedProperty` anymore. AFAICT this is only done for `get` anyway: https://github.com/machty/ember-concurrency/blob/624d747f82db20691ab70724dabe89233f367601/tests/types/ember-concurrency-test.ts#L797-L798
