### ISSUE TITLE
Issue with perform helper on rerouting to a page. (Ember 2.3.0)

### ISSUE THREAD

**Issue by adamdonahue** [machty/ember-concurrency#85]
We're seeing this when navigating away from controller using a task and then back again.  The first time the page loads everything runs fine, but when we move away and navigate back, we get this in the console:

ember.debug.js:6254 Uncaught Error: Assertion Failed: The first argument passed to the `perform` helper should be a Task object (without quotes); you passed undefined

Is this a known issue?  Race condition on task loading?

**Comment by adamdonahue** [comment]
This seems to be a more general issue than with `perform`.  The tasks defined on a controller are `undefined` once another route is loaded and then the controller's route reopened.

**Comment by machty** [comment]
You're using `.reopen()` on the controller every time you enter the route?

Have you only started seeing this for recent versions?

**Comment by adamdonahue** [comment]
I'm not using reopen.   Do I need to?  We just installed it for the first time.  Works great when the page is first loaded.  It's used as part of an input screen to a report with multiple tabs.  When I click to a new tab and then click back to the input tab, the tasks are set to undefined.

**Comment by adamdonahue** [comment]
I'll try to put together a Twiddle.

**Comment by adamdonahue** [comment]
Can't reproduce in a Twiddle.  This is very confusing.  I'm not sure what's going on.

**Comment by machty** [comment]
You should NOT use `reopen`, I misinterpreted when you said the "controller's route reopened".

I'm not sure what the issue is... it seems that there's a slice of time in which a reference to `someTask` is undefined. Perhaps it'd be easier to debug if you temporarily removed the `(perform)` helper and just displayed `{{someTask}}` on the page to see if it's actually getting set to undefined on the way back to the page or if continues to point to a task object. 

Also please let me know what version of ember-concurrency you're using and if previous versions of e-c were working correctly.

**Comment by adamdonahue** [comment]
Yeah, this is extremely odd.  Turns out it's only a couple of them that are undefined, and consistently, even though they are implemented exactly the same.  Further oddness is that I have an if test in the hbs that swaps between sets of buttons.  The ones that are included in the template (where the if succeeds on a call) get undefined next time around, but the others don't.  Finally if I remove the if they are all undefined.  This is extremely weird.

We installed yesterday to version 0.7.12.  I will try an earlier version to see if that helps with things.

Thanks for the feedback.  We'd really like this to work.

**Comment by machty** [comment]
Could you try 0.7.14 first? It's the newest code and fixes some issues people have been seeing recently. If that still doesn't work, please try 0.7.10 and let me know if it's still the same.

**Comment by adamdonahue** [comment]
I did, still broken.  I then tried 0.7.0, which didn't work at all (probably using something new in our code), but when I tried 0.7.5 it appears to work.  I'm going to bisect and I'll let you know which version introduced the issue.

**Comment by machty** [comment]
Please try `0.7.10`, not `0.7.0`, but failing that, yes, please bisect.

**Comment by adamdonahue** [comment]
I can confirm that the issues appears first in 0.7.11.  0.7.10 works.

**Comment by adamdonahue** [comment]
Next question is, what's special about 0.7.10? :-)

**Comment by machty** [comment]
Dang,`0.7.11` is where I introduced being able to do `this.myTask.perform()` instead of `this.get('myTask').perform()`. It specifically introduced [this defineProperty code](https://github.com/machty/ember-concurrency/blob/master/addon/-task-property.js#L435) which made the whole thing possible but has been causing tricky issues elsewhere. I have an idea of something that I might still need to fix, stay tuned.

**Comment by adamdonahue** [comment]
Yeah, I _just_ saw that.  Wondering if this was a good idea.  It's it a bit dangerous in case Ember internals change?  What was the problem with using `.get`?  I was going to ask why it was acceptable not to do that anyhow so interesting.  But if you can get it to work, fantastic.

Great stuff.

**Comment by machty** [comment]
We discussed this a bit more in `#e-concurrency` community Slack. I can reproduce this on Ember 2.3.0. Seems related to how Ember 2.3.0 tried to restore properties that'd been overwritten to enforce "mandatory setters". I have some ideas as to how to fix, will follow up shortly.

**Comment by machty** [comment]
Reverted the changes that were causing this in the latest version (0.7.15)
